/*
 * Copyright (C) Jessica LASSIE from 2020 to present
 * All rights reserved
 */
package fr.jl.cipher.view;

import fr.jl.cipher.controllers.crypting.Crypting;
import fr.jl.cipher.controllers.crypting.CryptingException;
import fr.jl.cipher.controllers.keys.KeysGenerators;
import java.io.IOException;
import java.security.InvalidAlgorithmParameterException;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;
import java.security.spec.InvalidKeySpecException;
import javax.crypto.BadPaddingException;
import javax.crypto.IllegalBlockSizeException;
import javax.crypto.NoSuchPaddingException;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 * HMI class
 */
public class JfEncryption extends javax.swing.JFrame {
    
    private static final String AES = "AES";
    private static final String RSA = "RSA";
    private static final String SRC_PATH = "src\\fr\\jl\\cipher\\resources\\";
    private static final String ERROR_ICON = "error_icon.png";
    private static final String SUCCESS_ICON = "success_icon.png";
    private static final String INFO_ICON = "info_icon.png";
    private static final String CIPHER_ICON = "cipher_icon.png";

    /**
     * Creates JFrame
     */
    public JfEncryption() {
        initComponents();
        
        buttonGroup.add(jRadioButtonDecrypt);
        buttonGroup.add(jRadioButtonEncrypt);
        jRadioButtonEncrypt.setSelected(true);
        jComboBoxAlgorithm.addItem(AES);
        jComboBoxAlgorithm.addItem(RSA);
        jTextFieldSelectedFile.setEditable(false);
        jTextFieldSelectedKey.setEditable(false);
        jButtonStart.setEnabled(false);
        jDialogSuccess.setLocationRelativeTo(this);
        jDialogInProgress.setLocationRelativeTo(this);
        jDialogError.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jFileChooser = new javax.swing.JFileChooser();
        jDialogSuccess = new javax.swing.JDialog();
        jLabelDialogSuccess = new javax.swing.JLabel();
        jButtonDialogSuccess = new javax.swing.JButton();
        jFileKeyChooser = new javax.swing.JFileChooser();
        jFolderGeneratedFilesKeysChooser = new javax.swing.JFileChooser();
        jDialogInProgress = new javax.swing.JDialog();
        jLabelDialogInProgress = new javax.swing.JLabel();
        jDialogError = new javax.swing.JDialog();
        jLabelDialogError = new javax.swing.JLabel();
        jButtonDialogError = new javax.swing.JButton();
        jLabelFile = new javax.swing.JLabel();
        jButtonStart = new javax.swing.JButton();
        jRadioButtonEncrypt = new javax.swing.JRadioButton();
        jRadioButtonDecrypt = new javax.swing.JRadioButton();
        jComboBoxAlgorithm = new javax.swing.JComboBox<>();
        jLabelEncrypt = new javax.swing.JLabel();
        jLabelKey = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jTextFieldSelectedKey = new javax.swing.JTextField();
        jTextFieldSelectedFile = new javax.swing.JTextField();
        jButtonSearchFile = new javax.swing.JButton();
        jButtonSearchKey = new javax.swing.JButton();
        jButtonGenerateKeys = new javax.swing.JButton();

        jDialogSuccess.setTitle("Success");
        jDialogSuccess.setIconImage(new ImageIcon(SRC_PATH + SUCCESS_ICON).getImage());
        jDialogSuccess.setLocation(new java.awt.Point(0, 0));
        jDialogSuccess.setModal(true);
        jDialogSuccess.setResizable(false);
        jDialogSuccess.setSize(new java.awt.Dimension(220, 150));

        jLabelDialogSuccess.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jButtonDialogSuccess.setText("OK");
        jButtonDialogSuccess.setAlignmentY(0.0F);
        jButtonDialogSuccess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDialogSuccessActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogSuccessLayout = new javax.swing.GroupLayout(jDialogSuccess.getContentPane());
        jDialogSuccess.getContentPane().setLayout(jDialogSuccessLayout);
        jDialogSuccessLayout.setHorizontalGroup(
            jDialogSuccessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogSuccessLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogSuccessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButtonDialogSuccess)
                    .addComponent(jLabelDialogSuccess, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE))
                .addContainerGap())
        );
        jDialogSuccessLayout.setVerticalGroup(
            jDialogSuccessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogSuccessLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelDialogSuccess, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonDialogSuccess)
                .addContainerGap())
        );

        jDialogInProgress.setTitle("Info");
        jDialogInProgress.setIconImage(new ImageIcon(SRC_PATH + INFO_ICON).getImage());
        jDialogInProgress.setLocation(new java.awt.Point(0, 0));
        jDialogInProgress.setResizable(false);
        jDialogInProgress.setSize(new java.awt.Dimension(220, 120));

        jLabelDialogInProgress.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jDialogInProgressLayout = new javax.swing.GroupLayout(jDialogInProgress.getContentPane());
        jDialogInProgress.getContentPane().setLayout(jDialogInProgressLayout);
        jDialogInProgressLayout.setHorizontalGroup(
            jDialogInProgressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogInProgressLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelDialogInProgress, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDialogInProgressLayout.setVerticalGroup(
            jDialogInProgressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogInProgressLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelDialogInProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDialogError.setTitle("Error");
        jDialogError.setIconImage(new ImageIcon(SRC_PATH + ERROR_ICON).getImage());
        jDialogError.setModal(true);
        jDialogError.setResizable(false);
        jDialogError.setSize(new java.awt.Dimension(250, 150));

        jLabelDialogError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jButtonDialogError.setText("OK");
        jButtonDialogError.setAlignmentY(0.0F);
        jButtonDialogError.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDialogErrorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogErrorLayout = new javax.swing.GroupLayout(jDialogError.getContentPane());
        jDialogError.getContentPane().setLayout(jDialogErrorLayout);
        jDialogErrorLayout.setHorizontalGroup(
            jDialogErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogErrorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButtonDialogError)
                    .addComponent(jLabelDialogError, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
                .addContainerGap())
        );
        jDialogErrorLayout.setVerticalGroup(
            jDialogErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogErrorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelDialogError, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jButtonDialogError)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cipher");
        setIconImage(new ImageIcon(SRC_PATH + CIPHER_ICON).getImage());
        setResizable(false);
        setSize(new java.awt.Dimension(431, 213));

        jLabelFile.setText("File *");

        jButtonStart.setText("Start");
        jButtonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartActionPerformed(evt);
            }
        });

        jRadioButtonEncrypt.setText("Encrypt");

        jRadioButtonDecrypt.setText("Decrypt");

        jLabelEncrypt.setText("Algorythm");

        jLabelKey.setText("Key *");

        jButtonSearchFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fr/jl/cipher/resources/search_icon.png"))); // NOI18N
        jButtonSearchFile.setToolTipText("Select a file");
        jButtonSearchFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchFileActionPerformed(evt);
            }
        });

        jButtonSearchKey.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fr/jl/cipher/resources/search_icon.png"))); // NOI18N
        jButtonSearchKey.setToolTipText("Select a key");
        jButtonSearchKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchKeyActionPerformed(evt);
            }
        });

        jButtonGenerateKeys.setText("Generate key(s)");
        jButtonGenerateKeys.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerateKeysActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jRadioButtonEncrypt)
                .addGap(75, 75, 75)
                .addComponent(jRadioButtonDecrypt)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelFile)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxAlgorithm, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabelKey)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jTextFieldSelectedKey, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonSearchKey)))
                                .addGap(1, 1, 1))
                            .addComponent(jSeparator2)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonStart, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldSelectedFile, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonSearchFile)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(43, 43, 43))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelEncrypt)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jButtonGenerateKeys, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator3))
                        .addGap(44, 44, 44))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabelEncrypt)
                .addGap(8, 8, 8)
                .addComponent(jComboBoxAlgorithm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonGenerateKeys)
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonEncrypt)
                    .addComponent(jRadioButtonDecrypt))
                .addGap(11, 11, 11)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabelKey)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSelectedKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSearchKey))
                .addGap(20, 20, 20)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelFile)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSelectedFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSearchFile))
                .addGap(27, 27, 27)
                .addComponent(jButtonStart)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartActionPerformed
        final String filePath = jTextFieldSelectedFile.getText();
        final String keyPath = jTextFieldSelectedKey.getText();
        final String algorithm = jComboBoxAlgorithm.getSelectedItem().toString();

        if (jRadioButtonEncrypt.isSelected()) {
            try {
                jLabelDialogInProgress.setText("Encryption in progress...");
                jDialogInProgress.setVisible(true);
                Crypting.encrypt(algorithm, filePath, keyPath);
                jDialogInProgress.setVisible(false);
                jLabelDialogSuccess.setText("File encrypted !");
                jDialogSuccess.setVisible(true);                
            } catch (ClassNotFoundException | InvalidKeySpecException | InvalidAlgorithmParameterException | IOException | InvalidKeyException | NoSuchAlgorithmException | BadPaddingException | IllegalBlockSizeException | NoSuchPaddingException | CryptingException e) {
                jLabelDialogError.setText(e.getMessage());
                jDialogError.setVisible(true);
            }
        } else {
            try {
                jLabelDialogInProgress.setText("Decryption in progress...");
                jDialogInProgress.setVisible(true);
                Crypting.decrypt(algorithm, filePath, keyPath);
                jDialogInProgress.setVisible(false);
                jLabelDialogSuccess.setText("File decrypted !");
                jDialogSuccess.setVisible(true);
            } catch (ClassNotFoundException | InvalidKeySpecException | InvalidAlgorithmParameterException | IOException | InvalidKeyException | NoSuchAlgorithmException | BadPaddingException | IllegalBlockSizeException | NoSuchPaddingException | CryptingException e) {
                jLabelDialogError.setText(e.getMessage());
                jDialogError.setVisible(true);
            }
        }
    }//GEN-LAST:event_jButtonStartActionPerformed

    private void jButtonDialogSuccessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDialogSuccessActionPerformed
        jDialogSuccess.setVisible(false);
    }//GEN-LAST:event_jButtonDialogSuccessActionPerformed

    private void jButtonSearchFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchFileActionPerformed
        final int value = jFileChooser.showOpenDialog(this);
        if(value == JFileChooser.APPROVE_OPTION){
            jTextFieldSelectedFile.setText(jFileChooser.getSelectedFile().getAbsolutePath());
            if(!jTextFieldSelectedKey.getText().equals("") && !jTextFieldSelectedFile.getText().equals("")) {
                jButtonStart.setEnabled(true);
            }
        }
    }//GEN-LAST:event_jButtonSearchFileActionPerformed

    private void jButtonSearchKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchKeyActionPerformed
        final int value = jFileKeyChooser.showOpenDialog(this);
        if(value == JFileChooser.APPROVE_OPTION){
            jTextFieldSelectedKey.setText(jFileKeyChooser.getSelectedFile().getAbsolutePath());
            if(!jTextFieldSelectedKey.getText().equals("") && !jTextFieldSelectedFile.getText().equals("")) {
                jButtonStart.setEnabled(true);
            }
        }
    }//GEN-LAST:event_jButtonSearchKeyActionPerformed

    private void jButtonGenerateKeysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerateKeysActionPerformed
        final String algorithm = jComboBoxAlgorithm.getSelectedItem().toString();
        jFolderGeneratedFilesKeysChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        final int value = jFolderGeneratedFilesKeysChooser.showSaveDialog(this);       
        if(value == JFileChooser.APPROVE_OPTION){
            try {
                jLabelDialogInProgress.setText("Generation of key(s) in progress...");
                jDialogInProgress.setVisible(true);
                String outputPath = jFolderGeneratedFilesKeysChooser.getSelectedFile().getAbsolutePath();
                KeysGenerators.generateAndSaveKeys(outputPath, algorithm);
                jDialogInProgress.setVisible(false);
                jLabelDialogSuccess.setText("Key(s) generated !");
                jDialogSuccess.setVisible(true);
            } catch (CryptingException | InvalidKeySpecException | NoSuchAlgorithmException | IOException e) {               
                jLabelDialogError.setText(e.getMessage());
                jDialogError.setVisible(true);
            }
        }        
    }//GEN-LAST:event_jButtonGenerateKeysActionPerformed

    private void jButtonDialogErrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDialogErrorActionPerformed
        jDialogError.setVisible(false);
    }//GEN-LAST:event_jButtonDialogErrorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfEncryption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new JfEncryption().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JButton jButtonDialogError;
    private javax.swing.JButton jButtonDialogSuccess;
    private javax.swing.JButton jButtonGenerateKeys;
    private javax.swing.JButton jButtonSearchFile;
    private javax.swing.JButton jButtonSearchKey;
    private javax.swing.JButton jButtonStart;
    private javax.swing.JComboBox<String> jComboBoxAlgorithm;
    private javax.swing.JDialog jDialogError;
    private javax.swing.JDialog jDialogInProgress;
    private javax.swing.JDialog jDialogSuccess;
    private javax.swing.JFileChooser jFileChooser;
    private javax.swing.JFileChooser jFileKeyChooser;
    private javax.swing.JFileChooser jFolderGeneratedFilesKeysChooser;
    private javax.swing.JLabel jLabelDialogError;
    private javax.swing.JLabel jLabelDialogInProgress;
    private javax.swing.JLabel jLabelDialogSuccess;
    private javax.swing.JLabel jLabelEncrypt;
    private javax.swing.JLabel jLabelFile;
    private javax.swing.JLabel jLabelKey;
    private javax.swing.JRadioButton jRadioButtonDecrypt;
    private javax.swing.JRadioButton jRadioButtonEncrypt;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextFieldSelectedFile;
    private javax.swing.JTextField jTextFieldSelectedKey;
    // End of variables declaration//GEN-END:variables

}
