/*
 * Copyright (C) Jessica LASSIE from 2020 to present
 * All rights reserved
 */
package fr.jl.cipher.view;

import fr.jl.cipher.controllers.crypting.Crypting;
import fr.jl.cipher.controllers.crypting.CryptingException;
import fr.jl.cipher.controllers.keys.KeysGenerators;
import java.io.IOException;
import java.security.InvalidAlgorithmParameterException;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;
import java.security.spec.InvalidKeySpecException;
import javax.crypto.BadPaddingException;
import javax.crypto.IllegalBlockSizeException;
import javax.crypto.NoSuchPaddingException;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 */
public class JfEncryption extends javax.swing.JFrame {
    
    private static final String AES = "AES";
    private static final String RSA = "RSA";
    private static final String SRC_PATH = "src\\fr\\jl\\cipher\\resources\\";
    private static final String ERROR_ICON = "error_icon.png";
    private static final String SUCCESS_ICON = "success_icon.png";
    private static final String CIPHER_ICON = "cipher_icon.png";

    /**
     * Creates JFrame
     */
    public JfEncryption() {
        initComponents();
        
        buttonGroup.add(jRadioButtonDecrypt);
        buttonGroup.add(jRadioButtonEncrypt);
        jRadioButtonEncrypt.setSelected(true);
        jComboBoxAlgorithm.addItem(AES);
        jComboBoxAlgorithm.addItem(RSA);
        jDialog.setSize(400, 140);
        jDialog.setLocationRelativeTo(null);
        jTextFieldSelectedFile.setEditable(false);
        jTextFieldSelectedKey.setEditable(false);
        jButtonStart.setEnabled(false);
        setLocationRelativeTo(null);
        setIconImage(new ImageIcon(SRC_PATH + CIPHER_ICON).getImage());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jFileChooser = new javax.swing.JFileChooser();
        jDialog = new javax.swing.JDialog();
        jLabelDialog = new javax.swing.JLabel();
        jButtonDialog = new javax.swing.JButton();
        jFileKeyChooser = new javax.swing.JFileChooser();
        jFolderGeneratedFilesKeysChooser = new javax.swing.JFileChooser();
        jLabelFile = new javax.swing.JLabel();
        jButtonClearFile = new javax.swing.JButton();
        jButtonStart = new javax.swing.JButton();
        jRadioButtonEncrypt = new javax.swing.JRadioButton();
        jRadioButtonDecrypt = new javax.swing.JRadioButton();
        jComboBoxAlgorithm = new javax.swing.JComboBox<>();
        jLabelEncrypt = new javax.swing.JLabel();
        jLabelKey = new javax.swing.JLabel();
        jButtonClearKey = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jTextFieldSelectedKey = new javax.swing.JTextField();
        jTextFieldSelectedFile = new javax.swing.JTextField();
        jButtonSearchFile = new javax.swing.JButton();
        jButtonSearchKey = new javax.swing.JButton();
        jButtonGenerateKeys = new javax.swing.JButton();

        jDialog.setTitle("Error");

        jLabelDialog.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jButtonDialog.setText("OK");
        jButtonDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDialogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogLayout = new javax.swing.GroupLayout(jDialog.getContentPane());
        jDialog.getContentPane().setLayout(jDialogLayout);
        jDialogLayout.setHorizontalGroup(
            jDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelDialog, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonDialog)
                .addGap(100, 100, 100))
        );
        jDialogLayout.setVerticalGroup(
            jDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jButtonDialog)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cipher");
        setResizable(false);
        setSize(new java.awt.Dimension(431, 213));

        jLabelFile.setText("File *");

        jButtonClearFile.setText("X");
        jButtonClearFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearFileActionPerformed(evt);
            }
        });

        jButtonStart.setText("Start");
        jButtonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartActionPerformed(evt);
            }
        });

        jRadioButtonEncrypt.setText("Encrypt");

        jRadioButtonDecrypt.setText("Decrypt");

        jLabelEncrypt.setText("Algorythm");

        jLabelKey.setText("Key *");

        jButtonClearKey.setText("X");
        jButtonClearKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearKeyActionPerformed(evt);
            }
        });

        jButtonSearchFile.setText("...");
        jButtonSearchFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchFileActionPerformed(evt);
            }
        });

        jButtonSearchKey.setText("...");
        jButtonSearchKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchKeyActionPerformed(evt);
            }
        });

        jButtonGenerateKeys.setText("Generate key(s)");
        jButtonGenerateKeys.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerateKeysActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonStart, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabelKey)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jTextFieldSelectedKey, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonSearchKey)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonClearKey))
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxAlgorithm, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(1, 1, 1))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldSelectedFile, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonSearchFile)
                                        .addGap(6, 6, 6))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelFile)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(jButtonClearFile))
                            .addComponent(jSeparator2))
                        .addGap(43, 43, 43))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelEncrypt)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jButtonGenerateKeys, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator3))
                        .addGap(44, 44, 44))))
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jRadioButtonEncrypt)
                .addGap(75, 75, 75)
                .addComponent(jRadioButtonDecrypt)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabelEncrypt)
                .addGap(8, 8, 8)
                .addComponent(jComboBoxAlgorithm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonGenerateKeys)
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonEncrypt)
                    .addComponent(jRadioButtonDecrypt))
                .addGap(11, 11, 11)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabelKey)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonClearKey, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldSelectedKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonSearchKey)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelFile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonClearFile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldSelectedFile)
                        .addComponent(jButtonSearchFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jButtonStart)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonClearFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearFileActionPerformed
        jTextFieldSelectedFile.setText("");
        if(jTextFieldSelectedKey.getText().equals("") || jTextFieldSelectedFile.getText().equals("")) {
            jButtonStart.setEnabled(false);
        }
    }//GEN-LAST:event_jButtonClearFileActionPerformed

    private void jButtonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartActionPerformed
        final String filePath = jTextFieldSelectedFile.getText();
        final String keyPath = jTextFieldSelectedKey.getText();
        final String algorithm = jComboBoxAlgorithm.getSelectedItem().toString();

        if (jRadioButtonEncrypt.isSelected()) {
            try {
                Crypting.encrypt(algorithm, filePath, keyPath);
                jDialog.setVisible(true);
                jLabelDialog.setText("Success");
                jDialog.setIconImage(new ImageIcon(SRC_PATH + SUCCESS_ICON).getImage());
            } catch (ClassNotFoundException | InvalidKeySpecException | InvalidAlgorithmParameterException | IOException | InvalidKeyException | NoSuchAlgorithmException | BadPaddingException | IllegalBlockSizeException | NoSuchPaddingException | CryptingException e) {
                jDialog.setVisible(true);
                jDialog.setIconImage(new ImageIcon(SRC_PATH + ERROR_ICON).getImage());
                jLabelDialog.setText(e.getMessage());
            }
        } else {
            try {
                Crypting.decrypt(algorithm, filePath, keyPath);
                jDialog.setVisible(true);
                jLabelDialog.setText("Success");
                jDialog.setIconImage(new ImageIcon(SRC_PATH + SUCCESS_ICON).getImage());
            } catch (ClassNotFoundException | InvalidKeySpecException | InvalidAlgorithmParameterException | IOException | InvalidKeyException | NoSuchAlgorithmException | BadPaddingException | IllegalBlockSizeException | NoSuchPaddingException | CryptingException e) {
                jDialog.setVisible(true);
                jDialog.setIconImage(new ImageIcon(SRC_PATH + ERROR_ICON).getImage());
                jLabelDialog.setText(e.getMessage());
            }
        }
    }//GEN-LAST:event_jButtonStartActionPerformed

    private void jButtonDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDialogActionPerformed
        jDialog.setVisible(false);
    }//GEN-LAST:event_jButtonDialogActionPerformed

    private void jButtonClearKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearKeyActionPerformed
        jTextFieldSelectedKey.setText("");
        if(jTextFieldSelectedKey.getText().equals("") || jTextFieldSelectedFile.getText().equals("")) {
            jButtonStart.setEnabled(false);
        }
    }//GEN-LAST:event_jButtonClearKeyActionPerformed

    private void jButtonSearchFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchFileActionPerformed
        final int value = jFileChooser.showOpenDialog(this);
        if(value == JFileChooser.APPROVE_OPTION){
            jTextFieldSelectedFile.setText(jFileChooser.getSelectedFile().getAbsolutePath());
            if(!jTextFieldSelectedKey.getText().equals("") && !jTextFieldSelectedFile.getText().equals("")) {
                jButtonStart.setEnabled(true);
            }
        }
    }//GEN-LAST:event_jButtonSearchFileActionPerformed

    private void jButtonSearchKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchKeyActionPerformed
        final int value = jFileKeyChooser.showOpenDialog(this);
        if(value == JFileChooser.APPROVE_OPTION){
            jTextFieldSelectedKey.setText(jFileKeyChooser.getSelectedFile().getAbsolutePath());
            if(!jTextFieldSelectedKey.getText().equals("") && !jTextFieldSelectedFile.getText().equals("")) {
                jButtonStart.setEnabled(true);
            }
        }
    }//GEN-LAST:event_jButtonSearchKeyActionPerformed

    private void jButtonGenerateKeysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerateKeysActionPerformed
        final String algorithm = jComboBoxAlgorithm.getSelectedItem().toString();
        jFolderGeneratedFilesKeysChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        final int value = jFolderGeneratedFilesKeysChooser.showSaveDialog(this);       
        if(value == JFileChooser.APPROVE_OPTION){
            try {
                String outputPath = jFolderGeneratedFilesKeysChooser.getSelectedFile().getAbsolutePath();
                KeysGenerators.generateAndSaveKeys(outputPath, algorithm);
                jDialog.setVisible(true);
                jLabelDialog.setText("Success");
                jDialog.setIconImage(new ImageIcon(SRC_PATH + SUCCESS_ICON).getImage());
            } catch (CryptingException | InvalidKeySpecException | NoSuchAlgorithmException | IOException e) {
                jDialog.setVisible(true);
                jDialog.setIconImage(new ImageIcon(SRC_PATH + ERROR_ICON).getImage());
                jLabelDialog.setText(e.getMessage());
            }
        }        
    }//GEN-LAST:event_jButtonGenerateKeysActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfEncryption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new JfEncryption().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JButton jButtonClearFile;
    private javax.swing.JButton jButtonClearKey;
    private javax.swing.JButton jButtonDialog;
    private javax.swing.JButton jButtonGenerateKeys;
    private javax.swing.JButton jButtonSearchFile;
    private javax.swing.JButton jButtonSearchKey;
    private javax.swing.JButton jButtonStart;
    private javax.swing.JComboBox<String> jComboBoxAlgorithm;
    private javax.swing.JDialog jDialog;
    private javax.swing.JFileChooser jFileChooser;
    private javax.swing.JFileChooser jFileKeyChooser;
    private javax.swing.JFileChooser jFolderGeneratedFilesKeysChooser;
    private javax.swing.JLabel jLabelDialog;
    private javax.swing.JLabel jLabelEncrypt;
    private javax.swing.JLabel jLabelFile;
    private javax.swing.JLabel jLabelKey;
    private javax.swing.JRadioButton jRadioButtonDecrypt;
    private javax.swing.JRadioButton jRadioButtonEncrypt;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextFieldSelectedFile;
    private javax.swing.JTextField jTextFieldSelectedKey;
    // End of variables declaration//GEN-END:variables

}
